# Generated by Django 2.1.8 on 2019-05-26 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditionname', models.CharField(max_length=255)),
                ('auditiontype', models.CharField(max_length=255)),
                ('auditionURL', models.URLField(blank=True, null=True)),
                ('entryDate', models.DateField()),
                ('auditiondescription', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'auditions',
                'db_table': 'audition',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventtitle', models.CharField(max_length=255)),
                ('eventlocation', models.TextField()),
                ('eventdate', models.DateField()),
                ('eventtime', models.TimeField()),
                ('eventdescription', models.TextField(blank=True, null=True)),
                ('eventURL', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'events',
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessontitle', models.CharField(max_length=255)),
                ('lessondate', models.DateField()),
                ('lessontime', models.TimeField()),
                ('location', models.TextField()),
                ('agenda', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'lessons',
                'db_table': 'lesson',
            },
        ),
    ]
